/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sijanstu.autoshare.version3.ui.portfolio;

import com.sijanstu.autoshare.version3.dto.portfolio.Stock;

import java.awt.*;

/**
 *
 * @author Sijan Bhandari
 */
public class ScripUI extends javax.swing.JPanel {

    /**
     * Creates new form ScripUI
     */
    public ScripUI() {
        initComponents();
    }
    public ScripUI(Stock stock){
        initComponents();
        name.setText(stock.getScript());
        balance.setText(String.valueOf(stock.getCurrentBalance()));
        previous.setText(stock.getPreviousClosingPrice());
        latest.setText(stock.getLastTransactionPrice());
        total.setText(stock.getValueAsOfLastTransactionPrice());
        if (stock.getScript()!=null){
            double previous=Double.parseDouble(stock.getPreviousClosingPrice());
            double latest=Double.parseDouble(stock.getLastTransactionPrice());
            if (previous>latest){
                setForeground(Color.red);
            }else if (previous<latest){
                setForeground(Color.green);
            }
            else{
                setForeground(Color.yellow);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        latest = new javax.swing.JLabel();
        previous = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 31, 31));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Sample");

        total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("9,776");

        balance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balance.setText("13");

        latest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        latest.setForeground(new java.awt.Color(255, 255, 255));
        latest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        latest.setText("752");

        previous.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        previous.setForeground(new java.awt.Color(255, 255, 255));
        previous.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previous.setText("752");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(latest, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(latest, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel balance;
    private javax.swing.JLabel latest;
    private javax.swing.JLabel name;
    private javax.swing.JLabel previous;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
