/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sijanstu.autoshare.version3.ui.ipoui;

/**
 *
 * @author Sijan Bhandari
 */
public class IPOList extends javax.swing.JPanel {

    /**
     * Creates new form IPOList
     */
    public IPOList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        iPOScripUI2 = new com.sijanstu.autoshare.version3.ui.ipoui.IPOScripUI();

        jScrollPane1.setBorder(null);

        jPanel1.add(iPOScripUI2);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sijanstu.autoshare.version3.ui.ipoui.IPOScripUI iPOScripUI2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
