package com.sijanstu.autoshare.version3.ui.ipoui;

import com.sijanstu.autoshare.version3.dto.ipo.IPOUser;

/**
 *
 * @author Sijan Bhandari
 */
public class UserSelection extends javax.swing.JPanel {
    private IPOUser user;
    public UserSelection() {
        initComponents();
    }

    public UserSelection(IPOUser user) {
        initComponents();
        checkbox.setText(user.getUsername());
        this.user=user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new com.sijanstu.autoshare.version3.ui.RoundPanel();
        checkbox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);

        roundPanel1.setBackground(new java.awt.Color(0, 0, 0));

        checkbox.setBackground(new java.awt.Color(0, 0, 0));
        checkbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkbox.setForeground(new java.awt.Color(255, 255, 255));
        checkbox.setText("546456");
        checkbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkbox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        checkbox.setOpaque(false);
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed

    }//GEN-LAST:event_checkboxActionPerformed
    public boolean isSelected() {
        return checkbox.isSelected();
    }
    public IPOUser getUser(){
        return user;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private com.sijanstu.autoshare.version3.ui.RoundPanel roundPanel1;

    public void setSelected(boolean selected) {
        checkbox.setSelected(selected);
    }
    // End of variables declaration//GEN-END:variables
}
