package com.sijanstu.autoshare.version3.ui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.sijanstu.autoshare.version3.dto.User;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 * @author Sijan Bhandari
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile(User user) {
        initComponents();
        setDark(true);
        populateTable(user);
    }

    void populateTable(User user) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        //add user data to table as columns
        model.setRowCount(0);
        model.addRow(new Object[]{"Name", user.getName()});
        model.addRow(new Object[]{"Email", user.getEmail()});
        model.addRow(new Object[]{"Username", user.getUsername()});
        model.addRow(new Object[]{"Address", user.getAddress()});
        model.addRow(new Object[]{"boid", user.getBoid()});
        model.addRow(new Object[]{"clientCode", user.getClientCode()});
        model.addRow(new Object[]{"contact", user.getContact()});
        model.addRow(new Object[]{"createdApproveDate", user.getCreatedApproveDate()});
        model.addRow(new Object[]{"createdApproveDateStr", user.getCreatedApproveDateStr()});
        model.addRow(new Object[]{"customerTypeCode", user.getCustomerTypeCode()});
        model.addRow(new Object[]{"demat", user.getDemat()});
        model.addRow(new Object[]{"dematExpiryDate", user.getDematExpiryDate()});
        model.addRow(new Object[]{"expiredDate", user.getExpiredDate()});
        model.addRow(new Object[]{"expiredDateStr", user.getExpiredDateStr()});
        model.addRow(new Object[]{"gender", user.getGender()});
        model.addRow(new Object[]{"id", user.getId()});
        model.addRow(new Object[]{"imagePath", user.getImagePath()});
        model.addRow(new Object[]{"meroShareEmail", user.getMeroShareEmail()});
        model.addRow(new Object[]{"passwordChangeDate", user.getPasswordChangeDate()});
        model.addRow(new Object[]{"passwordChangedDateStr", user.getPasswordChangedDateStr()});
        model.addRow(new Object[]{"passwordExpiryDate", user.getPasswordExpiryDate()});
        model.addRow(new Object[]{"passwordExpiryDateStr", user.getPasswordExpiryDateStr()});
        model.addRow(new Object[]{"profileName", user.getProfileName()});
        model.addRow(new Object[]{"renewedDate", user.getRenewedDate()});
        model.addRow(new Object[]{"renewedDateStr", user.getRenewedDateStr()});
        model.addRow(new Object[]{"status", user.getStatus()});

        //set table model
        table.setModel(model);

        //set table column width
        table.getColumnModel().getColumn(0).setPreferredWidth(150);
        table.getColumnModel().getColumn(1).setPreferredWidth(300);

        //set table column alignment
        table.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(new Color(0, 0, 0, 0));
                c.setForeground(Color.BLACK);
                return c;
            }
        });

        //sort table in ascending order
        table.setAutoCreateRowSorter(true);

        //sort table by column 0
        table.getRowSorter().toggleSortOrder(0);

        //set cell text color
        table.setForeground(Color.WHITE);

        //set text wrap
        table.setRowHeight(30);
        
    }

    public void setDark(boolean dark) {
        try {
            if (dark) {
                UIManager.setLookAndFeel(new FlatDarkLaf());
                FlatLaf.updateUI();
            } else {
                UIManager.setLookAndFeel(new FlatLightLaf());
                FlatLaf.updateUI();
            }
        } catch (UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Topics", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(User user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
